AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Lambda function to search for new .NET tweets and retweet
  them.
Resources:
  Retweet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: DotNetTwitterBot::DotNetTwitterBot.Functions::Retweet
      Runtime: dotnetcore3.1
      MemorySize: 128
      Timeout: 300
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Policies:
      - Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource: arn:aws:secretsmanager:ap-southeast-2:033094732892:secret:dotnet-twitter-bot-2VuMF5
